backend:
  name: git-gateway
  branch: main
media_folder: "/assets/images"
public_folder: "/assets/"
collections:
  - name: "blog"
    label: "Blog"
    folder: "app/content/blog"
    create: true
    slug: "---"
    fields:
        - { label: "title", name: "title", widget: "string" }
        - { label: "date", name: "date", widget: "date", format: 'YYYY-MM-DD' }
        - { label: "updated", name: "updated", widget: "date", format: 'YYYY-MM-DD', required: false}
        - { label: "intro", name: "intro", widget: "string" }
        - { label: "canonical", name: "canonical", widget: "string", required: false }
        - { label: "publication", name: "publication", widget: "string", required: false }
        - { label: "permalink", name: "permalink", widget: "string" }
        - { label: "tags", name: "tags", widget: "list" }
        - { label: "body", name: "body", widget: "markdown" }
  - name: "FAQs"
      label: "Fequently Asked Questions"
      file: "src/_data/faq.json"
      fields:
      - label: "Categories"
        name: "questionList"
        widget: "list"
        fields:
          - {label: "Question", name: "text", widget: "string"}
          - {label: "Answer", name: "answer", widget: "markdown"}